Feature/active enabled get components
Anders1232/RattletrapEngine pull request #27
Opened 2017-11-13 18:41 UTC by Anders1232

2017-11-14 00:11 UTC, bestknighter requested changes
- Tenta tirar o "/*" do makefile onde tem o rmdir e veja se funciona.
- O GameObject deve ser usado para cálculo de colisão quando está desativado? Ele não será renderizado...

2017-11-14 00:34 UTC, Anders1232 commented
Resolvido o problema do mdir. A lógica de colisão atualmente não está na engine, mas é responsabilidade de quem implementa o State.

2017-11-14 00:36 UTC, Anders1232 commented
Faz sentido, pois dependendo da State/Scene pode não ser necessário colisão, ou a colisão pode requerer um tratamento específico.

2017-11-14 00:36 UTC, bestknighter approved these changes
Ótimo!

2017-11-14 00:37 UTC, bestknighter commented
@Jato30 @VitorSDDF, vocês que estão responsáveis pelo ToM, discutam entre vocês sobre essa questão de GameObjects não-ativos serem considerados para colisão. Caso concluam que sim, eu e o @Anders1232 sugerimos usar o std::copy_if (dentro de <algorithm>) e passar o array copiado para o detector de colisões, para facilitar.

2017-11-14 00:44 UTC, bestknighter commented
Queremos saber a opinião de vocês dois também, @Jato30 e @VitorSDDF quanto a uma questão de liberdade x responsabilidade. O State::Update precisa executar algumas lógicas ANTES do Update dos filhos. Podemos forçar isso criando outras funções e fazendo ser virtual etc e tal, podemos entrar em detalhes depois. Ou podemos só mencionar na documentação e vocês tomarem cuidado na hora de implementar os Updates da vida. O que acham?

2017-11-19 00:22 UTC, Anders1232 commented
@VitorSDDF @mashiro11

2017-11-23 23:15 UTC, Jato30 commented
Se faz sentido existir algum GameObject sem colisão, então faz sentido colisão ser componente.

2017-11-23 23:29 UTC, Jato30 commented
Como o que a gente quer é a maior flexibilidade da engine, acredito que deixar assim pra cada filho implementar essas coisas que vc disse tira esse foco. Seria mais interessante a primeira opção mesmo.

2017-11-23 23:33 UTC, Jato30 commented
Não tenho mais como trabalhar até esse PR for aceito. Mudou muuuita coisa e não faz sentido adaptar o jogo pra algo que já tá ultrapassado.
Favor revisarem com urgência. @VitorSDDF @mashiro11

2017-11-23 23:34 UTC, merged